// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 13.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class AssetUtils {
  static const String package = 'digitalsaathi';

  static const String complainPng = 'assets/images/complain.png';

  static const String contentPng = 'assets/images/content.png';

  static const String logoPng = 'assets/images/logo.png';

  static const String logoutPng = 'assets/images/logout.png';

  static const String chatPng = 'assets/task_images/chat_icon.png';

  static const String meetingPng = 'assets/images/meeting.png';

  static const String meetingReportPng = 'assets/images/meeting_report.png';

  static const String newsPng = 'assets/images/news.png';

  static const String posterPng = 'assets/images/poster.png';

  static const String profilePng = 'assets/images/profile.png';

  static const String progressPng = 'assets/images/progress.png';

  static const String suggestionPng = 'assets/images/suggestion.png';

  static const String taskPng = 'assets/images/task.png';

  static const String workerReportPng = 'assets/images/worker_report.png';

  static const String National = 'assets/task_images/national.jpg';

  static const String State = 'assets/task_images/state.png';

  static const String DistrictParliament = 'assets/task_images/district_parliament .png';

  static const String AssemblyBlock = 'assets/task_images/assembly_block.png';

  static const String posterCheck = 'assets/task_images/poster_check.jpg';

  static const String FBLikeButton = 'assets/task_images/fb_like_button.png';

  static const String ShareArrow = 'assets/task_images/share_arrow.jpg';

  static const String CommentIcon = "assets/task_images/comment_icon.png";

  static const String Facebook = 'assets/task_images/facebook.png';

  static const String Instagram = 'assets/task_images/instagram.png';

  static const String Twitter = 'assets/task_images/twitter.png';

  static const String Whatsapp = 'assets/task_images/whatsapp.png';

  static const String SendIcon = 'assets/task_images/send.png';

  static const String ThreeDot = 'assets/task_images/threeDot.png';

  static const String PersonalDetails = 'assets/profile_images/personal_details.png';

  static const String IdCard = 'assets/profile_images/id_card.png';

  static const String AddFacebook = "assets/profile_images/facebook.png";

  static const String AddTwitter = 'assets/profile_images/twitter.png';

  static const String AddInstagram = 'assets/profile_images/instagram.png';

  static const String AddYouTube = 'assets/profile_images/youtube.png';

  static const String Progress = 'assets/profile_images/progress.png';

  static const String FollowMlaMp = 'assets/profile_images/mla_follow.png';

  static const String Faqs = 'assets/profile_images/faqs.png';

  static const String Voter = 'assets/profile_images/voter.png';

  static const String creatives = 'assets/profile_images/creative_one.jpg';

  static const String videos = 'assets/profile_images/videos.png';
  
  static const String shareIconWhite = 'assets/profile_images/share.png';

  static const String screenBackgroundTwo = 'assets/profile_images/screen_bg_two.jpg';

  static const String screenBackgroundFive = 'assets/profile_images/screen_bg_five.jpg';

  static const String screenBackgroundThree = 'assets/profile_images/screen_bg_three.jpg';

  static const String screenBackgroundSeven = 'assets/profile_images/screen_bg_seven.jpg';

  static const String screenBackgroundSix = 'assets/profile_images/screen_bg_six.jpg';

  static const String screenBackgroundFour = 'assets/profile_images/screen_bg_four.jpg';

  static const String screenBackgroundOne = 'assets/profile_images/screenbg_one.jpg';

  static const String messageSend = 'assets/profile_images/message_send.png';

  static const String bgCardOne = 'assets/profile_images/bg_card.jpg';

  static const String bgCardTwo = 'assets/profile_images/bg_card_two.jpg';

  static const String bgCardThree = 'assets/profile_images/bg_card_three.jpg';

  static const String bgCardFour = "assets/profile_images/bg_card_four.jpg";

  static const String bgCardFive = 'assets/profile_images/bg_card_five.jpg';

  static const String bgCardSix = 'assets/profile_images/bg_card_Six.jpg';

  static const String bgCardSeven = 'assets/profile_images/bg_card_seven.jpg';

  static const String bgCardNine = 'assets/profile_images/bg_card_nine.jpg';

  static const String bgCardTen = 'assets/profile_images/bg_card_ten.jpg';

  static const String bgMlaFollow = 'assets/profile_images/bg_mla_follow.jpg';

  static const String idCard = 'assets/profile_images/bg_id_card.png';

  static const String myPic = 'assets/profile_images/my_pic.png';


}
